__version__ = '0.0.1'

GEOMET_T, GEOCHEM_T = "GEOMET", "GEOCHEM"
MINERAL1_T, MINERAL2_T = "MINERAL1", "MINERAL2"
PORPHYRY_T = "PORPHYRY"

DATASETS = [
    GEOMET_T, 
    GEOCHEM_T,
    MINERAL1_T,
    MINERAL2_T,
    PORPHYRY_T
]

DATASET_SHORTS = {
    GEOMET_T: (GEOMET_T, "GMT"),
    GEOCHEM_T: (GEOCHEM_T, "GCH"),
    MINERAL1_T: (MINERAL1_T, "M1"),
    MINERAL2_T: (MINERAL2_T, "M1"),
    PORPHYRY_T: (PORPHYRY_T, "POR")
}

from .dataset import *